/**
 * Agent-bridge transport.
 *
 * Where no search API is reachable from the process — a sandbox with a
 * restrictive egress policy, for instance — the agent driving the run is the
 * only thing that can reach the web. This client reads results the agent
 * captured for engine-generated queries.
 *
 * The integrity property that makes this a fair test rather than a fixture:
 * a query with no capture is an ERROR, not an empty result. Silently
 * returning nothing would manufacture a false "researched and found nothing",
 * which is the one negative result that must always be real.
 *
 * The queries are generated by the engine and executed verbatim. The agent
 * chooses nothing about what is searched.
 */

import { readFileSync } from 'node:fs';

import type { SearchClient, SearchResult } from './types.ts';

export interface CaptureFile {
  /** When the capture was taken. */
  capturedAt: string;
  /** Tool or service the agent used to execute the queries. */
  transport: string;
  captures: { query: string; results: Omit<SearchResult, 'query'>[] }[];
}

export class AgentBridgeSearchClient implements SearchClient {
  readonly id = 'agent-bridge';
  readonly #byQuery = new Map<string, SearchResult[]>();
  readonly queriesRequested: string[] = [];

  constructor(capture: CaptureFile) {
    for (const entry of capture.captures) {
      this.#byQuery.set(
        entry.query,
        entry.results.map((result) => ({ ...result, query: entry.query })),
      );
    }
  }

  static fromFile(path: string): AgentBridgeSearchClient {
    return new AgentBridgeSearchClient(JSON.parse(readFileSync(path, 'utf8')) as CaptureFile);
  }

  async search(query: string): Promise<SearchResult[]> {
    this.queriesRequested.push(query);

    const captured = this.#byQuery.get(query);
    if (captured === undefined) {
      throw new Error(
        `no capture for query ${JSON.stringify(query)} — run it and add it to the capture ` +
          'file. An uncaptured query must never be reported as "found nothing".',
      );
    }

    return captured;
  }

  /** Captured queries never asked for — a sign the query generator changed. */
  unusedCaptures(): string[] {
    const requested = new Set(this.queriesRequested);
    return [...this.#byQuery.keys()].filter((q) => !requested.has(q));
  }
}
