/**
 * Pilot A LIVE — real research, no hand-built extraction fixture reused.
 *
 *   node scripts/pilot-a-live.ts
 *
 * Queries are generated by the engine and were executed verbatim; extraction
 * was done from those fresh results. The corpus run is printed alongside only
 * as a reference — nothing here is tuned to reproduce it.
 */

import { orbitalDirect, pilotATargets } from '../fixtures/pilot-a.ts';
import { liveCaptureV2, liveExtractionsV2 } from '../fixtures/pilot-a-live-v2.ts';
import { AgentBridgeSearchClient } from '../src/research/agent-bridge.ts';
import { CorpusClaimExtractor } from '../src/research/corpus.ts';
import { WebResearchAdapter } from '../src/research/adapter.ts';
import { runPipeline } from '../src/pipeline.ts';
import { supportingFacts } from '../src/claims.ts';
import { CostLedger } from '../src/providers/registry.ts';
import type { ClientProfile } from '../src/pipeline.ts';
import type { CompanyIdentity } from '../src/domain.ts';

const RUN_DATE = '2026-09-08';
const REPORTABLE_FLOOR = 60;

/** Cheap screen before any search: never spend research on a disqualified company. */
function prescreen(company: CompanyIdentity, _client: ClientProfile): string | null {
  const disqualified: Record<string, string> = {
    'bleckmann.com': 'third-party logistics provider — a competitor',
    'aldi.co.uk': 'enterprise retailer running its own distribution network',
  };
  const reason = disqualified[company.domain];
  return reason ? `${reason}; matches client disqualifier list` : null;
}

const search = new AgentBridgeSearchClient(liveCaptureV2);

const adapter = new WebResearchAdapter({
  search,
  extractor: new CorpusClaimExtractor(liveExtractionsV2),
  targets: pilotATargets,
  runDate: RUN_DATE,
  maxQueriesPerCompany: 2,
  prescreen,
});

const ledger = new CostLedger();
const started = Date.now();

const result = await runPipeline(adapter, {
  client: orbitalDirect,
  runDate: RUN_DATE,
  ledger: [],
  limit: 50,
  reportableFloor: REPORTABLE_FLOOR,
});

const elapsedMs = Date.now() - started;

for (const query of search.queriesRequested) {
  // Web search through the agent bridge costs no provider credits here; the
  // ledger still records the operation so cost per opportunity is measurable.
  ledger.record({ operation: 'agent-bridge.web_search', credits: 0, useful: true });
  void query;
}

const line = (char = '─') => console.log(char.repeat(78));

console.log('\nSIGNAL — PILOT A v2 (LIVE RESEARCH, IDENTITY-HARDENED)');
line('═');
console.log(`CLIENT:              ${orbitalDirect.name}`);
console.log(`DATE:                ${RUN_DATE}`);
console.log(`TRANSPORT:           ${liveCaptureV2.transport}`);
console.log(`COMPANIES IN SCOPE:  ${pilotATargets.length}`);
console.log(`QUERIES EXECUTED:    ${search.queriesRequested.length}`);
console.log(`PROVIDER CREDITS:    ${ledger.totalCredits()}`);
console.log(`PIPELINE TIME:       ${elapsedMs}ms`);
console.log(`REPORTED:            ${result.opportunities.length} (floor ${REPORTABLE_FLOOR})`);

console.log('\nFUNNEL');
line();
for (const [stage, count] of Object.entries(result.funnel)) {
  console.log(`  ${stage.padEnd(12)} ${count}`);
}

console.log('\nOPPORTUNITIES');
line('═');

for (const [index, opportunity] of result.opportunities.entries()) {
  const signal = adapter.signals().find((s) => s.company.domain === opportunity.company.domain)!;

  console.log(`\n${index + 1}. ${opportunity.company.name} — ${opportunity.score.total}/100 (raw ${opportunity.score.raw})`);
  console.log(`   ${opportunity.score.classification} · confidence ${opportunity.score.confidence}`);
  console.log(`   TRIGGER   ${signal.trigger} · event ${signal.eventDate ?? 'undated'} · ${signal.freshness.ageDays} days old`);
  console.log(`   CHANGED   ${signal.whatChanged}`);
  console.log(`   ROLE      ${signal.owningFunction.function}`);

  console.log('   FACTS');
  for (const f of supportingFacts(signal.hypothesis.id, signal.claims)) {
    console.log(`     • [tier ${f.source.tier}] ${f.source.publisher} — ${f.eventDate ?? 'undated'}`);
    console.log(`       ${f.statement.slice(0, 150)}${f.statement.length > 150 ? '…' : ''}`);
    console.log(`       ${f.source.url}`);
  }

  console.log('   HYPOTHESIS');
  console.log(`     ? ${signal.hypothesis.statement}`);
  console.log(`       test: ${signal.hypothesis.testableBy}`);

  for (const c of signal.contradictions) {
    console.log(`   ! [${c.severity}] ${c.note}`);
  }

  console.log(`   WHY NOW   ${signal.whyNow}`);
  console.log(`   ANGLE     ${signal.salesAngle}`);
  console.log(`   ACTION    ${opportunity.recommendedAction.action}`);
  console.log(`   SCORE     ${opportunity.score.explanation.join(' | ')}`);
}

console.log('\n\nREJECTED');
line('═');
for (const rejection of adapter.rejections()) {
  console.log(`\n  ${rejection.company.name} [${rejection.stage}] — ${rejection.queriesRun.length} queries`);
  console.log(`    ${rejection.reason}`);
}
for (const drop of result.dropped) {
  console.log(`\n  ${drop.company.name} [${drop.stage}]`);
  console.log(`    ${drop.reason}`);
}

console.log('\n\nIDENTITY GATE');
line('═');
let gateRejections = 0;
for (const signal of adapter.signals()) {
  for (const rejection of signal.identityRejections) {
    gateRejections += 1;
    console.log(`  ${signal.company.name}: REJECTED ${rejection.url}`);
    console.log(`    [${rejection.status}] ${rejection.explanation}`);
  }
}
for (const rejection of adapter.rejections()) {
  for (const item of rejection.identityRejections ?? []) {
    gateRejections += 1;
    console.log(`  ${rejection.company.name}: REJECTED ${item.url}`);
    console.log(`    [${item.status}] ${item.explanation}`);
  }
}
const acceptedSources = adapter.signals().reduce((a, s) => a + s.facts.length, 0);
console.log(`\n  sources accepted: ${acceptedSources} · rejected on identity: ${gateRejections}`);

console.log('\n\nSOURCES USED');
line('═');
const sources = new Map<string, number>();
for (const signal of adapter.signals()) {
  for (const f of signal.facts) {
    sources.set(f.source.publisher, (sources.get(f.source.publisher) ?? 0) + 1);
  }
}
for (const [publisher, count] of [...sources].sort((a, b) => b[1] - a[1])) {
  console.log(`  ${String(count).padStart(2)} × ${publisher}`);
}

console.log('\n\nUNUSED CAPTURES (queries captured but never requested)');
line('═');
const unused = search.unusedCaptures();
console.log(unused.length === 0 ? '  none' : unused.map((q) => `  ${q}`).join('\n'));
console.log();
