/**
 * Pilot A LIVE — captured 2026-09-08.
 *
 * Fourteen queries, generated by `buildQueries` and executed verbatim through
 * the agent bridge (no search API is reachable from this process: the egress
 * gateway returns 403 for every search host). The engine chose what to search;
 * the agent was transport only.
 *
 * Extraction was done from these fresh results. Where it disagrees with
 * fixtures/pilot-a.ts, the live reading wins — the fixture is a reference
 * point, not a target, and the engine has not been tuned toward it.
 */

import type { Fact, Hypothesis, Inference, SourceAttribution } from '../src/domain.ts';
import type { CaptureFile } from '../src/research/agent-bridge.ts';
import type { ExtractionCorpus } from '../src/research/corpus.ts';
import { toSource } from '../src/research/sources.ts';
import type { ClaimTopic } from '../src/research/registry.ts';
import { asClaims } from './legacy-adapter.ts';

const RUN_DATE = '2026-09-08';

function fact(
  id: string,
  statement: string,
  url: string,
  eventDate?: string,
  originId?: string,
  ownedDomains?: string[],
): Fact {
  return {
    kind: 'fact',
    id,
    statement,
    source: toSource(url, { ownedDomains }, originId),
    ...(eventDate ? { eventDate } : {}),
    discoveredAt: RUN_DATE,
    verification: 'search_summary_only',
  };
}

const inf = (id: string, statement: string, derivedFrom: string[], reasoning: string): Inference => ({
  kind: 'inference',
  id,
  statement,
  derivedFrom,
  reasoning,
});

const hyp = (
  id: string,
  statement: string,
  derivedFrom: string[],
  reasoning: string,
  testableBy: string,
): Hypothesis => ({ kind: 'hypothesis', id, statement, derivedFrom, reasoning, testableBy });


/**
 * What each source states about the company it is describing — read from the
 * result title and snippet, independently of the target. This is the input to
 * the identity gate, so it must never be derived from the target fingerprint:
 * that would make every source trivially match itself.
 */
function withAttribution(
  facts: Fact[],
  stated: Omit<SourceAttribution, 'url'>,
  topic: ClaimTopic = 'general',
) {
  return asClaims(facts, stated, topic);
}

/** Results as returned, trimmed to those that carried a claim. */
export const liveCapture: CaptureFile = {
  capturedAt: RUN_DATE,
  transport: 'agent WebSearch tool (no search API reachable from process)',
  captures: [
    {
      query: 'Maeving Ltd Coventry news announcement expansion contract',
      results: [
        {
          title: 'Maeving in the right direction: E-motorbike maker gears up exports with UKEF backing',
          url: 'https://www.gov.uk/government/news/maeving-in-the-right-direction-e-motorbike-maker-gears-up-exports-with-ukef-backing',
          snippet:
            'Coventry-based Maeving secured a £3m trade finance facility backed by UK Export Finance to meet growing demand in the US, Germany and France, creating 13 new jobs.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'Maeving secures £8 Million to accelerate global expansion and new model development',
          url: 'https://thepack.news/maeving-secures-8-million-to-accelerate-global-expansion-and-new-model-development/',
          snippet: 'Maeving raised £8m to boost production and accelerate entry into overseas markets.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Maeving Ltd export growth or new overseas market entry',
      results: [
        {
          title: "UK Motorcycle Manufacturing: Maeving's £11m Export Power-Play",
          url: 'https://thegrowthhub.me/maeving-electric-motorcycle-manufacturing-investment-west-midlands-uk/',
          snippet:
            'Maeving started exporting to California, Germany and France in 2023 and exports around half of its bikes; the US is now its largest international market, with sales up fivefold this year versus 2024.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'UK e-motorbike maker Maeving secures £8m to fuel growth and overseas expansion',
          url: 'https://bmmagazine.co.uk/get-funded/uk-e-motorbike-maker-maeving-secures-8m-to-fuel-growth-and-overseas-expansion/',
          snippet: 'Round completed in September 2025.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Baltex Ilkeston, Derbyshire news announcement expansion contract',
      results: [
        {
          title: 'Baltex secures seven-figure funding to drive European expansion',
          url: 'https://www.themanufacturer.com/articles/baltex-secures-seven-figure-funding-to-drive-european-expansion/',
          snippet:
            'Seven-figure HSBC UK package; TradePay facilities support EU imports and exports; spending split between Ilkeston and Łódź, Poland.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Baltex export growth or new overseas market entry',
      results: [
        {
          title: "UK's Baltex accelerates international growth strategy",
          url: 'https://knittingindustry.com/uks-baltex-accelerates-international-strategy/',
          snippet:
            'Baltex is now also targeting the USA market following an approval from aircraft manufacturer Boeing, and expects 20% export growth over the next 12 months.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Bramble Group Market Harborough news announcement expansion contract',
      results: [
        {
          title: 'Family Food Business Opens Landmark Distribution Centre',
          url: 'https://www.ldc.co.uk/news/family-food-business-opens-landmark-distribution-centre/',
          snippet:
            'Bramble Foods opened a 67,000 sq ft national distribution centre, Lancaster House, at Airfield Business Park; opened alongside managing director Tony Foster, finance director Chris Neville and sales director Ken Osborne.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'Bramble Foods opens new distribution hub and eyes expansion',
          url: 'https://www.grocerygazette.co.uk/2026/07/31/bramble-foods-opens-new-distribution-hub-and-eyes-expansion/',
          snippet:
            'The site becomes the main UK distribution hub, increasing warehousing and stockholding capacity as it expands product range and customer base. Group employs ~300, expects up to 50 more roles.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      // Identity collision: matched Brambles Ltd (CHEP), an unrelated
      // Australian pallet company. Nothing usable about the target.
      query: 'Bramble Group export growth or new overseas market entry',
      results: [
        {
          title: 'Brambles Strategy and Business Model',
          url: 'https://umbrex.com/resources/company-profiles/brambles-ltd/',
          snippet:
            'Brambles operates in 60 countries through its CHEP brand — a different company from Bramble Group of Market Harborough.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'deVOL Kitchens Loughborough news announcement expansion contract',
      results: [
        {
          title: "Luxury kitchen supplier's expansion is a recipe for success",
          url: 'https://www.matherjamie.co.uk/latest-news/luxury-kitchen-supplier-s-expansion-is-a-recipe-for-success/',
          snippet:
            'deVOL Kitchens bought the 40,000 sq ft former Karl Mayer factory on Kings Road, Shepshed for £1.95m, comprising 37,000 sq ft industrial space plus offices and a loading yard.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'deVOL Kitchens export growth or new overseas market entry',
      results: [
        {
          title: 'We won a King\'s Award! - The deVOL Journal',
          url: 'https://www.devolkitchens.co.uk/blog/we-won-a-kings-award',
          snippet:
            'deVOL has grown overseas revenue by 2,300% over the last 6 years, with 31% of sales now exported; orders received from over 35 countries, with new overseas markets established in Thailand, China and Denmark.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'DeVOL Kitchens honoured with King\'s Award for Enterprise',
          url: 'https://kbbfocus.com/news/3895-devol-kitchens-honoured-with-kings-award-for-enterprise',
          snippet: 'King\'s Award for Enterprise for International Trade, for continuous growth in overseas sales.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'NMS International Group Market Harborough news announcement expansion contract',
      results: [
        {
          title: 'NMS INTERNATIONAL GROUP LTD overview - GOV.UK',
          url: 'https://find-and-update.company-information.service.gov.uk/company/06360525',
          snippet: 'Company record only. No dated commercial announcement surfaced.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      // Identity collision: matched NMS Industries (Chinese mining equipment)
      // and NMS Consulting. Nothing about the Market Harborough company.
      query: 'NMS International Group export growth or new overseas market entry',
      results: [
        {
          title: 'NMS Secures Major Overseas Order Valued at CNY 149 Million',
          url: 'https://www.nmsindustries.com/news/20250224/',
          snippet:
            'NMS Industries — a different company from NMS International Group of Market Harborough.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Winbro Group Technologies Shepshed news announcement expansion contract',
      results: [
        {
          title: "Government Minister opens Winbro's new Advanced Machining centre",
          url: 'https://www.quaser.com/blog/news-2/government-minister-opens-winbros-new-advanced-machining-centre-83',
          snippet: 'A 43,000 sq ft advanced machining facility in Shepshed — opened 2015.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'Winbro Group Technologies 2026 Company Profile',
          url: 'https://pitchbook.com/profiles/company/130557-16',
          snippet:
            'Technology Centre expansion dates from 2023; acquired by Quaser Machine Tools in October 2020.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Winbro Group Technologies export growth or new overseas market entry',
      results: [
        {
          title: 'Winbro Group Technologies - Company Profile',
          url: 'https://www.crunchbase.com/organization/winbro-group-technologies',
          snippet: 'Directory profile. No dated export or market-entry announcement.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      query: 'Slack & Parr Kegworth news announcement expansion contract',
      results: [
        {
          title: 'Slack & Parr weighs up job losses at Kegworth facility',
          url: 'https://www.insidermedia.com/news/midlands/slack-parr-weighs-up-jobs-losses-at-kegworth-facility',
          snippet:
            'Slack & Parr has confirmed it is considering the loss of up to 40 roles at Kegworth, citing dramatically slowing investment in Chinese and Far East markets, tariffs imposed in new export markets, and significant increases in domestic business costs.',
          retrievedAt: RUN_DATE,
        },
        {
          title: 'Hayward Tyler buys Slack & Parr out of administration',
          url: 'https://www.scottishfinancialnews.com/articles/glasgow-based-hayward-tyler-buys-slack-parr-out-of-administration',
          snippet: 'Administration July 2023; acquired by Avingtrans subsidiary August 2023.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
    {
      // Identity collision: "Slack" matched academic literature on slack
      // resources in exporting firms.
      query: 'Slack & Parr export growth or new overseas market entry',
      results: [
        {
          title: 'Untangling the multiple effects of slack resources on exporting behavior',
          url: 'https://www.sciencedirect.com/science/article/abs/pii/S1090951617305059',
          snippet: 'Academic paper on organisational slack — not the target company.',
          retrievedAt: RUN_DATE,
        },
      ],
    },
  ],
};

export const liveExtractions: ExtractionCorpus = {
  'maeving.com': {
    trigger: 'export_finance',
    whatChanged:
      '£3m UKEF-backed trade finance facility to build production capacity for the US, Germany and France, adding 13 jobs, against US sales already up fivefold year on year.',
    polarity: 'demand_increasing',
    polarityRationale:
      'legacy capture: polarity recorded before rationale was a required field',
    consequence: {
      actionable: true,
      rationale:
        'Funded export scale-up on a regulated cargo type: more consignments, more documentation.',
    },
    claims: withAttribution([
      fact(
        'lv-maeving-f1',
        'Maeving secured a £3m trade finance facility from HSBC UK, backed by UK Export Finance, to invest in production capacity for demand in the US, Germany and France, creating 13 new jobs at Coventry.',
        'https://www.gov.uk/government/news/maeving-in-the-right-direction-e-motorbike-maker-gears-up-exports-with-ukef-backing',
        '2026-08-15',
        'ukef-maeving-release',
      ),
      fact(
        'lv-maeving-f2',
        'Maeving began exporting to California, Germany and France in 2023, now exports around half of its bikes, and US sales have risen fivefold this year compared with 2024.',
        'https://thegrowthhub.me/maeving-electric-motorcycle-manufacturing-investment-west-midlands-uk/',
        '2026-08-15',
      ),
      fact(
        'lv-maeving-f3',
        'Maeving raised £8m in a round completed September 2025 to boost production and accelerate entry into overseas markets.',
        'https://bmmagazine.co.uk/get-funded/uk-e-motorbike-maker-maeving-secures-8m-to-fuel-growth-and-overseas-expansion/',
        '2025-09-30',
      ),
    ], { statedName: 'Maeving', statedGeography: { country: 'United Kingdom', town: 'Coventry' }, statedIndustry: 'electric motorbike manufacturing' }, 'export_trade'),
    inferences: [
      inf(
        'lv-maeving-i1',
        'Consignment volume on established US and European lanes is rising steeply — fivefold on the US lane already — with funded capacity behind it.',
        ['lv-maeving-f1', 'lv-maeving-f2'],
        'The company reports the fivefold US increase itself, and the facility funds capacity to serve it.',
      ),
    ],
    hypothesis: hyp(
      'lv-maeving-h1',
      'Freight arrangements sized for 2023-era export volumes are being asked to carry several times that, on a regulated cargo type — which is when rates, consolidation and DG documentation get reopened.',
      ['lv-maeving-i1'],
      'Growth of this rate on an existing lane changes the economics of how it should be shipped, even where a forwarder is already in place.',
      'Ask what their US shipping cadence looks like now versus last year, and whether the current arrangement was priced before the fivefold increase.',
    ),
    owningFunction: {
      function: 'Operations / Supply Chain',
      rationale:
        'Export capacity and DG compliance at this size sit with operations; the funding announcement is a finance event but the freight decision is not.',
    },
    icpRelevance: {
      fits: true,
      rationale:
        'Coventry manufacturer of physical goods, exporting around half its output, scaling on funded capacity.',
    },
    contradictions: [
      {
        severity: 'caveat',
        note:
          'CORRECTS THE FIXTURE: Maeving is not a domestic-first shipper. It has exported since 2023 and sends roughly half its bikes abroad, so an incumbent forwarder is near-certain and this is a displacement conversation. The fixture inferred a first-time exporter and was wrong.',
      },
    ],
    judgements: { icpFit: 22, signalStrength: 16, commercialRelevance: 13 },
    whyNow:
      'US sales are up fivefold year on year and in August 2026 Maeving took £3m of UKEF-backed finance to fund the capacity behind that. Freight arrangements set up when they started exporting in 2023 are now carrying several times the volume.',
    salesAngle:
      "Your US sales are up fivefold and you've just funded the capacity to go further. Worth asking whether your shipping was priced for the volume you had in 2023 or the volume you have now — and we can look at the Class 9 documentation side while we're at it.",
  },

  'baltex.co.uk': {
    trigger: 'new_market_entry',
    whatChanged:
      'Targeting the USA market following Boeing approval, alongside a seven-figure HSBC package funding EU trade flows and a stated 20% export growth target.',
    polarity: 'demand_increasing',
    polarityRationale:
      'legacy capture: polarity recorded before rationale was a required field',
    consequence: {
      actionable: true,
      rationale:
        'A new US lane plus 20% more EU volume is new freight to be arranged.',
    },
    claims: withAttribution([
      fact(
        'lv-baltex-f1',
        'Baltex secured a seven-figure HSBC UK package; TradePay facilities support EU imports and exports, with spending split between Ilkeston and Łódź, Poland.',
        'https://www.themanufacturer.com/articles/baltex-secures-seven-figure-funding-to-drive-european-expansion/',
        '2026-07-20',
        'hsbc-baltex-release',
      ),
      fact(
        'lv-baltex-f2',
        'Baltex is now also targeting the USA market following an approval from aircraft manufacturer Boeing, and expects 20% export growth over the next 12 months.',
        'https://knittingindustry.com/uks-baltex-accelerates-international-strategy/',
        '2026-07-20',
      ),
    ], { statedName: 'Baltex', statedGeography: { country: 'United Kingdom', region: 'Derbyshire', town: 'Ilkeston' }, statedIndustry: 'technical textiles' }, 'export_trade'),
    inferences: [
      inf(
        'lv-baltex-i1',
        'A Boeing approval opens a US aerospace lane that did not previously exist, on top of a fifth more volume across existing EU and UK–Poland routes.',
        ['lv-baltex-f1', 'lv-baltex-f2'],
        'Aerospace qualification is what gates entry to that supply chain; the company names the USA as a new target on the back of it.',
      ),
    ],
    hypothesis: hyp(
      'lv-baltex-h1',
      'A brand-new US aerospace lane needs freight and customs arrangements that do not exist yet, and aerospace consignments carry documentation and traceability requirements beyond ordinary export paperwork.',
      ['lv-baltex-i1'],
      'A new market entry is a genuine greenfield freight requirement, unlike volume growth on an established lane.',
      'Ask whether US shipments have started yet and who is handling the first ones — before it is handled, this is open; after, it is displacement.',
    ),
    owningFunction: {
      function: 'Supply Chain',
      rationale:
        'Dual-site UK/Poland manufacturing plus a new export destination puts the routing and customs decision with supply chain.',
    },
    icpRelevance: {
      fits: true,
      rationale:
        'Derbyshire technical textiles manufacturer with UK and Polish production, active EU trade flows and a newly opened US market.',
    },
    contradictions: [
      {
        severity: 'caveat',
        note:
          'Multiple outlets carried this from one HSBC release — one independent source, not several. Baltex is a long-established exporter to the EU, so only the US lane is genuinely new.',
      },
    ],
    judgements: { icpFit: 23, signalStrength: 18, commercialRelevance: 14 },
    whyNow:
      'Baltex has cleared Boeing approval and named the USA as a new target market, on top of a July 2026 HSBC package funding EU trade and a stated 20% export growth target. A US aerospace lane is a route they have not shipped before.',
    salesAngle:
      "Boeing approval opens a US lane you haven't run before. First shipments into an aerospace supply chain are where documentation and traceability trip people up — worth a conversation before the first one goes, not after.",
  },

  'bramblefoods.co.uk': {
    trigger: 'new_premises',
    whatChanged:
      'Opened Lancaster House, a 67,000 sq ft main UK distribution hub, expanding product range and customer base with up to 50 new roles.',
    polarity: 'demand_increasing',
    polarityRationale:
      'legacy capture: polarity recorded before rationale was a required field',
    consequence: {
      actionable: true,
      rationale:
        'Storage is closed, but outbound volume and Q4 peak overflow both grow.',
    },
    claims: withAttribution([
      fact(
        'lv-bramble-f1',
        'Bramble Foods opened a 67,000 sq ft national distribution centre, Lancaster House, at Airfield Business Park, opened alongside managing director Tony Foster, finance director Chris Neville and sales director Ken Osborne.',
        'https://www.ldc.co.uk/news/family-food-business-opens-landmark-distribution-centre/',
        '2026-07-31',
      ),
      fact(
        'lv-bramble-f2',
        'The site becomes the main UK distribution hub, increasing warehousing and stockholding capacity as the group expands product range and customer base; around 300 employed, up to 50 more roles expected.',
        'https://www.grocerygazette.co.uk/2026/07/31/bramble-foods-opens-new-distribution-hub-and-eyes-expansion/',
        '2026-07-31',
      ),
    ], { statedName: 'Bramble Foods', statedGeography: { country: 'United Kingdom', town: 'Market Harborough' }, statedIndustry: 'fine food manufacturing and distribution' }, 'premises'),
    inferences: [
      inf(
        'lv-bramble-i1',
        'Core warehousing has just been solved in-house, so storage is closed; what grows instead is despatch volume across a widening customer base.',
        ['lv-bramble-f1', 'lv-bramble-f2'],
        'A purpose-built main hub replaces third-party storage, but a wider range and customer base means more outbound movements from it.',
      ),
    ],
    hypothesis: hyp(
      'lv-bramble-h1',
      'The opportunity is outbound haulage and seasonal peak overflow rather than storage — a hub sized for the average will be tested by a food-gifting Q4.',
      ['lv-bramble-i1'],
      'Storage is the obvious pitch and it is the one thing they have just bought themselves out of.',
      'Ask what they did for overflow last November and whether Lancaster House changes that answer.',
    ),
    owningFunction: {
      function: 'Operations',
      rationale:
        'Despatch and capacity planning for the new hub sit with operations. Notably the coverage names the MD, finance director and sales director — but no operations owner, which is the recurring pattern.',
    },
    icpRelevance: {
      fits: true,
      rationale: 'PE-backed Leicestershire food manufacturer and distributor with pronounced seasonal peaks.',
    },
    contradictions: [
      {
        severity: 'caveat',
        note:
          'The signal is a company solving its own warehousing problem, which closes the obvious storage pitch. Survives on peak overflow and outbound haulage only.',
      },
      {
        severity: 'caveat',
        note:
          'IDENTITY: the trigger query for this company returned Brambles Ltd (CHEP pallets, Australia) — an unrelated business. No claim was taken from it.',
      },
    ],
    judgements: { icpFit: 20, signalStrength: 12, commercialRelevance: 10 },
    whyNow:
      'Bramble opened its main UK distribution hub on 31 July while expanding range and customer base. The building is sized for the average; food gifting is not an average business in Q4.',
    salesAngle:
      "You've just opened Lancaster House, so storage isn't the conversation. Overflow and vehicles for the Christmas peak might be — and that's a September conversation, not a December one.",
  },

  'devolkitchens.com': {
    trigger: 'new_market_entry',
    whatChanged:
      'Established new overseas markets in Thailand, China and Denmark, with 31% of sales now exported and overseas revenue up 2,300% over six years; recognised by a King\'s Award for International Trade.',
    polarity: 'demand_increasing',
    polarityRationale:
      'legacy capture: polarity recorded before rationale was a required field',
    consequence: {
      actionable: true,
      rationale:
        'New Asian and Nordic lanes need crating and consolidation decisions now.',
    },
    claims: withAttribution([
      fact(
        'lv-devol-f1',
        'deVOL has grown overseas revenue by 2,300% over the last six years, with 31% of sales now exported, orders received from over 35 countries, and new overseas markets established in Thailand, China and Denmark.',
        'https://www.devolkitchens.co.uk/blog/we-won-a-kings-award',
        '2026-05-06',
      ),
      fact(
        'lv-devol-f2',
        'deVOL Kitchens was honoured with a King\'s Award for Enterprise for International Trade for continuous growth in overseas sales.',
        'https://kbbfocus.com/news/3895-devol-kitchens-honoured-with-kings-award-for-enterprise',
        '2026-05-06',
      ),
      fact(
        'lv-devol-f3',
        'deVOL Kitchens bought the 40,000 sq ft former Karl Mayer factory on Kings Road, Shepshed for £1.95m, comprising 37,000 sq ft of industrial space plus offices and a loading yard.',
        'https://www.matherjamie.co.uk/latest-news/luxury-kitchen-supplier-s-expansion-is-a-recipe-for-success/',
        undefined,
      ),
    ], { statedName: 'deVOL Kitchens', statedGeography: { country: 'United Kingdom', town: 'Loughborough' }, statedIndustry: 'handmade kitchens and interiors' }, 'export_trade'),
    inferences: [
      inf(
        'lv-devol-i1',
        'New lanes to Thailand, China and Denmark have been opened recently, alongside an established US flow, for bulky fragile cabinetry made in Leicestershire.',
        ['lv-devol-f1', 'lv-devol-f2'],
        'The company names those three as newly established markets, distinct from the mature US business.',
      ),
    ],
    hypothesis: hyp(
      'lv-devol-h1',
      'Newly opened Asian and Nordic lanes mean crating, consolidation and customs decisions being made now for destinations the existing US-focused arrangement was not built for.',
      ['lv-devol-i1'],
      'Route economics and packing standards that work for New York do not transfer to Bangkok or Shanghai.',
      'Ask who is handling the Thailand and China consignments and whether that is the same arrangement as the US.',
    ),
    owningFunction: {
      function: 'Operations / Logistics',
      rationale: 'Export despatch and packing standards sit with operations, not the showroom side.',
    },
    icpRelevance: {
      fits: true,
      rationale:
        'Loughborough manufacturer of bulky, fragile, high-value goods, exporting 31% of sales, two miles from the client.',
    },
    contradictions: [
      {
        severity: 'caveat',
        note:
          'A long-established exporter with 31% of sales overseas certainly has incumbent forwarders. The new-market element is what is fresh; the award itself is not a trigger.',
      },
      {
        severity: 'caveat',
        note:
          'The Shepshed factory purchase is undated in available sources and may be historic. It is carried as context, not as the trigger.',
      },
    ],
    judgements: { icpFit: 23, signalStrength: 15, commercialRelevance: 13 },
    whyNow:
      'deVOL has just established new overseas markets in Thailand, China and Denmark, on top of 31% of sales already exported. Those are lanes nobody has set up yet, for a product where crating decides whether it arrives saleable.',
    salesAngle:
      "You've opened Thailand, China and Denmark on top of the US business. Those routes crate and consolidate differently to New York — and we're at the other end of Loughborough if you want someone to look at a load before it ships.",
  },

  // Researched; the only current material was a company record and two
  // collisions with unrelated firms. No dated commercial change.
  'nmsinfrastructure.com': null,

  // Researched; every event found dates from 2015-2023.
  'winbrogroup.com': null,

  'slackandparr.com': {
    trigger: 'contraction',
    whatChanged:
      'Considering the loss of up to 40 roles at Kegworth, citing slowing Chinese and Far East investment, tariffs in new export markets and rising domestic costs.',
    polarity: 'demand_reducing',
    polarityRationale:
      'legacy capture: polarity recorded before rationale was a required field',
    consequence: {
      actionable: false,
      rationale:
        'Export volumes are contracting and cost is being cut: freight demand is falling, so there is nothing here for this client to sell into. A cost-reduction vendor would read this differently.',
    },
    claims: withAttribution([
      fact(
        'lv-slackparr-f1',
        'Slack & Parr has confirmed it is considering the loss of up to 40 roles at its Kegworth facility, citing dramatically slowing investment in Chinese and Far East markets, the imposition of tariffs in new export markets, and significant increases in domestic business costs.',
        'https://www.insidermedia.com/news/midlands/slack-parr-weighs-up-jobs-losses-at-kegworth-facility',
        '2026-08-20',
      ),
    ], { statedName: 'Slack & Parr', statedGeography: { country: 'United Kingdom', town: 'Kegworth' }, statedIndustry: 'precision pump manufacturing' }, 'restructuring'),
    inferences: [
      inf(
        'lv-slackparr-i1',
        'Export volumes to their principal overseas markets are falling, not rising, and the cost base is under active reduction.',
        ['lv-slackparr-f1'],
        'Redundancy consultation attributed to slowing overseas investment and tariffs describes contracting trade, not growing trade.',
      ),
    ],
    hypothesis: hyp(
      'lv-slackparr-h1',
      'There is no freight opportunity here: shipping volume is contracting and the company is cutting cost, which makes this a supplier-squeeze situation rather than a buying situation.',
      ['lv-slackparr-i1'],
      'A company reducing headcount because export demand fell is not about to add a logistics supplier.',
      'Revisit if export volumes recover or the restructure completes and growth resumes.',
    ),
    owningFunction: { function: 'n/a', rationale: 'No opportunity to own.' },
    icpRelevance: {
      fits: true,
      rationale:
        'Kegworth precision manufacturer five miles from the client — the profile fits, which is exactly why the contraction matters.',
    },
    contradictions: [
      {
        severity: 'fatal',
        note:
          'The only current signal is contraction: redundancy consultation for up to 40 roles driven by falling overseas demand and tariffs. Demand for freight is going down, not up.',
      },
    ],
    judgements: { icpFit: 21, signalStrength: 0, commercialRelevance: 0 },
    whyNow: 'n/a — negative signal.',
    salesAngle: 'n/a — do not approach on a growth premise.',
  },
};
